name: Build and Release VSIX

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install
      
    - name: Compile TypeScript
      run: yarn run compile
      
    - name: Run linting
      run: yarn run lint
      
    - name: Run tests
      run: yarn run test
      continue-on-error: true  # Tests might fail in CI environment
      
    - name: Package VSIX
      run: yarn vsce package
      
    - name: Get package info
      id: package
      run: |
        VERSION=$(node -p "require('./package.json').version")
        NAME=$(node -p "require('./package.json').name")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "name=$NAME" >> $GITHUB_OUTPUT
        echo "filename=$NAME-$VERSION.vsix" >> $GITHUB_OUTPUT
        
    - name: Upload VSIX as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.package.outputs.filename }}
        path: "*.vsix"
        retention-days: 30
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: "*.vsix"
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}